const messages = ([reset, retry, retryUnknown, cancel, cancelled, skipped, unsupported, failed]: readonly [string, string, string, string, string, string, string, string]) => ({
  'chat.usageLimit.reset': reset,
  'chat.usageLimit.retry': retry,
  'chat.usageLimit.retryUnknown': retryUnknown,
  'chat.usageLimit.cancel': cancel,
  'chat.usageLimit.cancelled': cancelled,
  'chat.usageLimit.skipped': skipped,
  'chat.usageLimit.unsupported': unsupported,
  'chat.usageLimit.failed': failed,
});

export const usageLimitRetryI18n = {
  en: messages(['Usage resets at {time}.', 'Retry scheduled for {time}.', 'Retry scheduled for {time}. If the limit persists, retry every 30 minutes.', 'Cancel retry', 'Automatic retry cancelled.', 'No automatic retry. The reset is more than 10 hours away.', 'Automatic retry is unavailable in VS Code.', 'Could not update retry status. The retry may still be scheduled.']),
  de: messages(['Das Nutzungslimit wird am {time} zurückgesetzt.', 'Erneuter Versuch für {time} geplant.', 'Erneuter Versuch für {time} geplant. Bei fortbestehendem Limit wird alle 30 Minuten erneut versucht.', 'Wiederholung abbrechen', 'Automatische Wiederholung abgebrochen.', 'Keine automatische Wiederholung. Das Limit wird erst in mehr als 10 Stunden zurückgesetzt.', 'Automatische Wiederholungen sind in VS Code nicht verfügbar.', 'Der Wiederholungsstatus konnte nicht aktualisiert werden. Die Wiederholung kann weiterhin geplant sein.']),
  nl: messages(['De gebruikslimiet wordt hersteld op {time}.', 'Nieuwe poging gepland voor {time}.', 'Nieuwe poging gepland voor {time}. Als de limiet blijft gelden, volgt elke 30 minuten een nieuwe poging.', 'Nieuwe poging annuleren', 'Automatische nieuwe poging geannuleerd.', 'Geen automatische nieuwe poging. Het herstel duurt nog meer dan 10 uur.', 'Automatisch opnieuw proberen is niet beschikbaar in VS Code.', 'De status kon niet worden bijgewerkt. De nieuwe poging kan nog gepland staan.']),
  es: messages(['El límite se restablece el {time}.', 'Reintento programado para {time}.', 'Reintento programado para {time}. Si el límite persiste, se reintentará cada 30 minutos.', 'Cancelar reintento', 'Reintento automático cancelado.', 'No habrá reintento automático. Faltan más de 10 horas para el restablecimiento.', 'El reintento automático no está disponible en VS Code.', 'No se pudo actualizar el estado. El reintento podría seguir programado.']),
  fr: messages(['Le quota sera réinitialisé le {time}.', 'Nouvelle tentative prévue le {time}.', 'Nouvelle tentative prévue le {time}. Si la limite persiste, une nouvelle tentative aura lieu toutes les 30 minutes.', 'Annuler la tentative', 'Nouvelle tentative automatique annulée.', 'Aucune tentative automatique. La réinitialisation est dans plus de 10 heures.', 'Les nouvelles tentatives automatiques ne sont pas disponibles dans VS Code.', 'Impossible de mettre à jour le statut. La tentative peut toujours être prévue.']),
  ja: messages(['使用制限は {time} にリセットされます。', '{time} に再試行します。', '{time} に再試行します。制限が続く場合は30分ごとに再試行します。', '再試行をキャンセル', '自動再試行をキャンセルしました。', 'リセットまで10時間を超えているため、自動再試行は行いません。', 'VS Codeでは自動再試行を利用できません。', '再試行の状態を更新できませんでした。再試行が引き続き予定されている可能性があります。']),
  ko: messages(['사용 한도는 {time}에 초기화됩니다.', '{time}에 재시도할 예정입니다.', '{time}에 재시도할 예정입니다. 한도가 계속되면 30분마다 재시도합니다.', '재시도 취소', '자동 재시도가 취소되었습니다.', '초기화까지 10시간 넘게 남아 있어 자동 재시도하지 않습니다.', 'VS Code에서는 자동 재시도를 사용할 수 없습니다.', '재시도 상태를 업데이트하지 못했습니다. 재시도가 여전히 예약되어 있을 수 있습니다.']),
  pl: messages(['Limit zostanie zresetowany {time}.', 'Ponowna próba zaplanowana na {time}.', 'Ponowna próba zaplanowana na {time}. Jeśli limit nadal obowiązuje, próby będą ponawiane co 30 minut.', 'Anuluj ponowną próbę', 'Automatyczna ponowna próba anulowana.', 'Brak automatycznej próby. Reset nastąpi za ponad 10 godzin.', 'Automatyczne ponawianie nie jest dostępne w VS Code.', 'Nie udało się zaktualizować stanu. Ponowna próba może nadal być zaplanowana.']),
  'pt-BR': messages(['O limite será redefinido em {time}.', 'Nova tentativa agendada para {time}.', 'Nova tentativa agendada para {time}. Se o limite persistir, haverá uma nova tentativa a cada 30 minutos.', 'Cancelar nova tentativa', 'Nova tentativa automática cancelada.', 'Sem nova tentativa automática. A redefinição ocorrerá em mais de 10 horas.', 'A nova tentativa automática não está disponível no VS Code.', 'Não foi possível atualizar o estado. A nova tentativa pode continuar agendada.']),
  tr: messages(['Kullanım sınırı {time} tarihinde sıfırlanacak.', 'Yeniden deneme {time} için planlandı.', 'Yeniden deneme {time} için planlandı. Sınır devam ederse her 30 dakikada bir yeniden denenecek.', 'Yeniden denemeyi iptal et', 'Otomatik yeniden deneme iptal edildi.', 'Otomatik yeniden deneme yok. Sıfırlamaya 10 saatten fazla var.', 'VS Code içinde otomatik yeniden deneme kullanılamaz.', 'Yeniden deneme durumu güncellenemedi. Yeniden deneme hâlâ planlanmış olabilir.']),
  uk: messages(['Ліміт використання скинеться {time}.', 'Повторну спробу заплановано на {time}.', 'Повторну спробу заплановано на {time}. Якщо ліміт зберігається, спроби повторюватимуться кожні 30 хвилин.', 'Скасувати повторну спробу', 'Автоматичну повторну спробу скасовано.', 'Автоматичної повторної спроби не буде. До скидання понад 10 годин.', 'Автоматичні повторні спроби недоступні у VS Code.', 'Не вдалося оновити стан. Повторна спроба може залишатися запланованою.']),
  'zh-CN': messages(['使用限额将于 {time} 重置。', '已安排在 {time} 重试。', '已安排在 {time} 重试。如果仍受限，将每30分钟重试一次。', '取消重试', '已取消自动重试。', '不会自动重试。距离重置还有超过10小时。', 'VS Code 不支持自动重试。', '无法更新重试状态。重试可能仍在计划中。']),
  'zh-TW': messages(['使用限額將於 {time} 重設。', '已安排在 {time} 重試。', '已安排在 {time} 重試。如果仍受限，將每30分鐘重試一次。', '取消重試', '已取消自動重試。', '不會自動重試。距離重設還有超過10小時。', 'VS Code 不支援自動重試。', '無法更新重試狀態。重試可能仍在排程中。']),
};
